### ISSUE TITLE
parallel_cucumber doesn't do the scenarios per process calculation properly if cucumber profiles are used instead of tags

### ISSUE THREAD

**Issue by sandeepnagra** [badoo/parallel_cucumber#29]
It does the calculation correctly if only tags are used but if a profile defined in cucumber.yml is used which has all the tags defined, it fails to calculate exactly how many scenarios will be executed so it does the calculation based on all the scenarios in the project across all feature files due to which the allocation of tests is per process is done incorrectly causing the execution to take more time than expected as tests within a process are executed sequentially.

For example, if my project has total 400 scenarios but I have a profile with which only 40 scenarios should run when I do `parallel_cucumber -n 10 '-p test_profile_name'` it will say `10 processes for 400 scenarios, ~ 40 scenarios per process`

For the same test if I use the tags like: `parallel_cucumber -n 10 '-t @abc -t ~@xyz'` it will do the calculation correctly and say: `10 processes for 40 scenarios, ~ 4 scenarios per process`

**Comment by Vikquick** [comment]
Problem still appears

**Comment by bayandin** [comment]
Hey @sandeepnagra @Vikquick, it seems your issue related to another project: [parallel_tests](https://github.com/grosser/parallel_tests) (it has binary with the same name`parallel_cucumber`, but works in a different way). Please fill free to raise (or [transfer](https://help.github.com/en/articles/transferring-an-issue-to-another-repository)) the issue.

**Comment by sandeepnagra** [comment]
Yup. I forked parallel_tests repo and fixed this issue. Forgot to close this issue.

**Comment by Vikquick** [comment]
> Yup. I forked parallel_tests repo and fixed this issue. Forgot to close this issue.

Can you explain how you fixed issue in parallel_tests repo?

**Comment by sandeepnagra** [comment]
@Vikquick - here's my PR with the fix in parallel_tests gem https://github.com/grosser/parallel_tests/pull/668/files

If you use parallel_tests gem now, it works with new cucumber tag expression syntax.
