### ISSUE TITLE
parallel_cucumber needs tag formatting update to match new tagging style of cucumber 3.0

### ISSUE THREAD

**Issue by sandeepnagra** [badoo/parallel_cucumber#30]
New conditional operator tagging style in cucumber 3.0 allows user to set tags like `--tags @abc and @def not @123 not @xyz`

parallel_cucumber doesn't like this formatting and miscalculates the scenarios per process for total scenarios in the project rather the actual count scenarios that satisfies the tag conditions.

**Comment by bayandin** [comment]
Hey @sandeepnagra it seems the issue related to another repo: https://github.com/grosser/parallel_tests
